### ISSUE TITLE
Go: func keyword name function name are of same color

### ISSUE THREAD

**Issue by abhimanyu003** [aslbarnett/lapis-vscode#52]
Awesome theme and colors. 
Really like it, I have one small trouble that for GOLang: `func` keyword and function name are of the same color.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/265913/197062806-8fa3e9cf-6581-4bd6-b58c-62ed096c41d3.png">

**This is from default vscode theme**

<img width="734" alt="image" src="https://user-images.githubusercontent.com/265913/197063017-6b9bab96-580a-4410-9c09-4917a514e047.png">

**Comment by aslbarnett** [comment]
Thanks for spotting that! I have fixed this in: 63d143cdd5689c139dc12e2c2955866cbf8f5d5b and this has been released to Visual Studio Code as version 1.6.8.

<img width="430" alt="Screenshot 2022-10-21 at 10 38 01" src="https://user-images.githubusercontent.com/18450058/197165246-ab556022-85f7-4a33-b9bc-345122facc13.png">
