### ISSUE TITLE
Default prompt message cannot be seen clearly

### ISSUE THREAD

**Issue by photon808** [aslbarnett/lapis-vscode#70]
In the `PORTS` panel, after clicking on `Forward a Port`, the default prompt in the **text field** in the Port column cannot be seen clearly.
This also happens to the default prompts in the other text fields.

![image](https://github.com/user-attachments/assets/7222da53-9a08-4819-9e70-416086c2d2e7)

**Comment by aslbarnett** [comment]
Thanks very much for raising this! I have updated the placeholder text color to make it more readable and a new version of the theme is on the marketplace 😊.

**Comment by photon808** [comment]
Amazing! Appreciate your great work!
